// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string event_best_combo = "CgkI6OiY098SEAIQBg"; // <GPGSID>
        public const string achievement_3600sec = "CgkI6OiY098SEAIQCw"; // <GPGSID>
        public const string event_death = "CgkI6OiY098SEAIQBA"; // <GPGSID>
        public const string event_ads_tap = "CgkI6OiY098SEAIQBQ"; // <GPGSID>
        public const string leaderboard_best_score = "CgkI6OiY098SEAIQEA"; // <GPGSID>
        public const string achievement_100_death = "CgkI6OiY098SEAIQDQ"; // <GPGSID>
        public const string event_play_combo_score = "CgkI6OiY098SEAIQCA"; // <GPGSID>
        public const string event_total_combo_score = "CgkI6OiY098SEAIQBw"; // <GPGSID>
        public const string event_play_score = "CgkI6OiY098SEAIQAg"; // <GPGSID>
        public const string leaderboard_best_combo = "CgkI6OiY098SEAIQEQ"; // <GPGSID>
        public const string achievement_over_the_rainbow = "CgkI6OiY098SEAIQCg"; // <GPGSID>
        public const string event_total_score = "CgkI6OiY098SEAIQAQ"; // <GPGSID>
        public const string event_best_score = "CgkI6OiY098SEAIQAw"; // <GPGSID>
        public const string event_normal_mode = "CgkI6OiY098SEAIQCQ"; // <GPGSID>

}

